services:
  al-carbon-calculator:
    container_name: al-carbon-calculator
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
    networks:
      - carbon-calc
  mongo:
    container_name: mongo-carbon-calc-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "my_volume_mongodb:/data/db"
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - carbon-calc

networks:
  carbon-calc:
    driver: bridge

volumes:
  my_volume_mongodb: